### ISSUE TITLE
Running on a Raspberry Pi / ARMv7 build

### ISSUE THREAD

**Issue by jfml** [Kizaing/KavitaDocker#1]
Would it be possible to get an ARMv7 build to get this running on a RPI4? At least that's what I think what the problem is, when I try tun the nightly image I get an error saying:

ERROR: no matching manifest for linux/arm/v7 in the manifest list entries

Thanks a lot! ^__^

**Comment by Kizaing** [comment]
Hi, thanks for using the image! There seems to be an issue with Dotnet and Docker's multi-arch tools when compiling specifically for armv7, but I am trying to work out the kinks on that haha. There will be a Pi build coming! I will close the issue once its fixed

**Comment by jfml** [comment]
Hi, thanks for the super quick answer and all the hard work! Looking forward to trying out Kavita ^__^

**Comment by Kizaing** [comment]
Took some work, but I got it! The nightly tag now includes armv7 as well as arm64 support, closing the issue :)

**Comment by jfml** [comment]
That was so fast, amazing! It works for me, thanks a lot! ^__^
